# -*- coding: utf-8 -*-
"""Var_Linguistic_predef.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OHdP_F3MLg3Co314ZzK5LtjLCfbmR488
"""

from . import conjuntos_fuzzy as cf
from . import variables_linguisticas as vl

class CrearVariablesLinguisticas:
    @staticmethod
    def crear(Values):
        variables_linguisticas = {}
        for atributo, (vmin, vmax) in Values.items():
            mid = (vmin + vmax) / 2
            bajo = cf.TriangleFuzzySet(vmin, vmin, mid, term="BAJO")
            medio = cf.TriangleFuzzySet(vmin, mid, vmax, term="MEDIO")
            alto = cf.TriangleFuzzySet(mid, vmax, vmax, term="ALTO")

            L = vl.LinguisticVariable(
                [bajo, medio, alto],
                concept=f"CONJUNTOS FUZZY {atributo.upper()}",
                universe_of_discourse=[vmin, vmax]
            )

            variables_linguisticas[atributo] = L

        return variables_linguisticas




class joinVar:
    @staticmethod
    def join(*linguistic_vars):
        variables_dict = {}
        for L in linguistic_vars:
            # ✅ Soporta tanto concept como _concept
            if getattr(L, "concept", None):
                key = L.concept
            elif getattr(L, "_concept", None):
                key = L._concept
            else:
                key = f"atributo{len(variables_dict)+1}"  # sin guion bajo
            variables_dict[key] = L
        return variables_dict



